version: '3'

services:
  script:
    container_name: script
    build:
      context: .
      dockerfile: Docker-script
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dmitrii
      POSTGRES_PASSWORD: dmitrii
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      VALUE: 'SUNSHINE'
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: dmitrii@boom.com
      PGADMIN_DEFAULT_PASSWORD: dmitrii
    ports:
      - '5050:80'

  db:
    container_name: db
    build:
      context: .
      dockerfile: Docker-db
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: dmitrii
      POSTGRES_PASSWORD: dmitrii
    ports:
      - "5432:5432"
volumes:
  db_data: 