FROM python:3.8-slim
MAINTAINER Dmitries
LABEL version='1.0'
RUN apt-get update && \
    apt-get install -y python3 && \
    useradd -m dmitrii
USER dmitrii
COPY app.py /home/app.py
ENV PERSON_NAME='Dmitrii'  
WORKDIR /home
ENTRYPOINT ["python3", "app.py"]