name: lab3 

on:
  push:
    branches: ["main"]
    paths:
      - "lab3/**"
      - ".github/workflows/**"

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    defaults:
      run:
        working-directory: "/lab3"

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: dockerhub login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build docker image and push to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./lab3
          file: ./Dockerfile-hello-user
          push: true
          tags: dramaerr/hello-user-image:latest, dramaerr/hello-user-image:version-${{ github.run_number }}
